### ISSUE TITLE
DateTime slots are created in database as Timestamp columns instead of DateTimes

### ISSUE THREAD

**Issue by sanavarali** [fenix-framework/fenix-framework#199]

**Comment by jcarvalho** [comment]
Just a heads up on the progress, implementing this change is proving a bit trickier than expected, as OJB does not recognize the `DATETIME` type, but it's nothing that can't be fixed :)

**Comment by jcarvalho** [comment]
While far from ideal, the solution for this issue was implemented in f00e30dc98897d9a8ac9783087556dac0ab30f9a.

I will be testing this change for a while, and once I'm confident that everything keeps working with it, I'll close this issue.

**Comment by jcarvalho** [comment]
This has been fixed in the 2.6.1 release.

**Comment by sergiofbsilva** [comment]
@sanavarali do you remember what was the real motivation for this ?

**Comment by sanavarali** [comment]
@sergiofbsilva this issue appeared because minimum value of TIMESTAMP in mysql is only 1970-01-01 (vs. 1000-01-01 of DATETIME)
