### ISSUE TITLE
Unexpected results with mariaDB

### ISSUE THREAD

**Issue by pabrantes** [fenix-framework/fenix-framework#206]
#### Preamble
[TransactionManager](https://github.com/fenix-framework/fenix-framework/blob/develop/backend/jvstm-ojb/runtime/src/main/java/pt/ist/fenixframework/backend/jvstmojb/pstm/TransactionChangeLogs.java) contains two queries that  use date conditions: 

1. One that [deletes records from FF$LAST_TX_PROCESSED on bootstrap](https://github.com/fenix-framework/fenix-framework/blob/develop/backend/jvstm-ojb/runtime/src/main/java/pt/ist/fenixframework/backend/jvstmojb/pstm/TransactionChangeLogs.java#L293) 
2. Other that [selects the minimum TX_NUMBER to clean things from FF$TX_CHANGE_LOGS](https://github.com/fenix-framework/fenix-framework/blob/develop/backend/jvstm-ojb/runtime/src/main/java/pt/ist/fenixframework/backend/jvstmojb/pstm/TransactionChangeLogs.java#L337)

#### The problem 

We've observed that when running this queries in server ***MariaDB 5.5.41*** this two queries do not perform as expected. Although while testing the same queries in mySQL we had no problems at all (as expected). It seems the problem is that mariaDB is considering the value as a string instead of a date.

Here is an example, first we select everything to show you the content of FF$LAST_TX_PROCESS. This already shows some unexpected data since we have entries between 14 September to 11 September (for a single AS) which should have been deleted by the query that cleans these registers at boostrap:

*MariaDB [sandbox_test]> select * FROM FF$LAST_TX_PROCESSED;*

 SERVER                                                       | LAST_TX | LAST_UPDATE         
-----------------------------------------------------------|---------|---------------------
 tomcat@10.100.23.50:test-web-app:566a00f7:14fcc43d162:-8000  |  230256 | 2015-09-14 17:05:05 
 tomcat@10.100.23.50:test-web-app:-31e385fd:14fc81fa9f8:-8000 |  229999 | 2015-09-14 15:29:17 
 tomcat@10.100.23.50:test-web-app:-220c7682:14fbe5c33e8:-8000 |  227671 | 2015-09-12 13:22:42|
 tomcat@10.100.23.50:test-web-app:-337d445a:14fc183d375:-8000 |  228901 | 2015-09-13 20:10:55 
 tomcat@10.100.23.50:test-web-app:-4e22e90:14fba4c49d1:-8000  |  227114 | 2015-09-11 22:40:54 
5 rows in set (0.00 sec)

Now we use the condition used in the query to select the minimum tx number (240 = 2*SECONDS_BETWEEN_UPDATES)

*MariaDB [sandbox_test]> select * FROM FF$LAST_TX_PROCESSED WHERE LAST_UPDATE > NOW() - 240;*

SERVER                                                 | LAST_TX | LAST_UPDATE         
-----------------------------------------------------|---------------|---------------------
 tomcat@10.100.23.50:test-web-app:566a00f7:14fcc43d162:-8000   |  230256 | 2015-09-14 17:05:05 
 tomcat@10.100.23.50:test-web-app:-31e385fd:14fc81fa9f8:-8000    |  229999 | 2015-09-14 15:29:17 
 tomcat@10.100.23.50:test-web-app:-220c7682:14fbe5c33e8:-8000 |  227671 | 2015-09-12 13:22:42
 tomcat@10.100.23.50:test-web-app:-337d445a:14fc183d375:-8000 |  228901 | 2015-09-13 20:10:55 
 tomcat@10.100.23.50:test-web-app:-4e22e90:14fba4c49d1:-8000   |  227114 | 2015-09-11 22:40:54 

5 rows in set, **1 warning** (0.00 sec)

Noticed the warning? So did I... so if we check the warnings with a show warnings:

*MariaDB [sandbox_test]> show warnings;*

 Level   | Code | Message                                    
---------|------|--------------------------------------------
 Warning | 1292 | Incorrect datetime value: '20150915115363' |

The dangerous part is that if I keep doing several queries from time to time I actually get the correct result. This can also be seen in the query logs if we go look for the DELETE queries in the FF$TX_CHANGE_LOGS where we see queries where the TX_NUMBER goes down instead of going up.

### Impact

With this kind of behavior the table FF$TX_CHANGE_LOGS keeps growing and renders the system useless with long queries in FF$TX_CHANGE_LOGS locking the table and making all writes fail.

### Suggestion to fix 

Since these queries are already using NOW() which is a mysql/mariaDB function and are not 100% portable to other BDs I'll allow myself to use the other functions from this realm (having in mind that I'm making it even worst to make this query portable but currently without better options).

MariaDB and mySQL both have the same date functions

            | MariaDB | Mysql
----------|-------------|-----------
To subtract | [Check docs](https://mariadb.com/kb/en/mariadb/date_sub/) | [Check docs](https://dev.mysql.com/doc/refman/5.5/en/date-and-time-functions.html#function_date-sub)
To add | [Check docs](https://mariadb.com/kb/en/mariadb/date_add/) | [Check docs](https://dev.mysql.com/doc/refman/5.5/en/date-and-time-functions.html#function_date-add)

In the current case both queries are doing subtractions so the main fix is instead of using the condition NOW () - X (where X is in seconds) use the following condition ***DATE_SUB(NOW(), INTERVAL X DAY_SECOND)***

**Comment by jcarvalho** [comment]
This alternative syntax seems to work without warnings, and delivering the correct results:

`select * FROM FF$LAST_TX_PROCESSED WHERE LAST_UPDATE > NOW() - interval 240 second;`.

As there are other places within the backend that already use this syntax, it would be preferred over the alternative function.

**Comment by pabrantes** [comment]
@jcarvalho as long as it works (and it seems it does) it's fine by me. Can you already provide a timeframe for when will this bug fix be released?

**Comment by jcarvalho** [comment]
Closed by #207.
