### ISSUE TITLE
How do you define abstract interfaces in DML?

### ISSUE THREAD

**Issue by Maslor** [fenix-framework/fenix-framework#210]
The examples seen in the DML's documentation I've read cover most usage in terms of defining normal classes or subclasses but I didn't find any example concerning the usage of abstract classes, specifically abstract interfaces. 
Could you please enlighten me on this subject?

**Comment by jcarvalho** [comment]
The DML is targeted at defining persistent domain entities, it does not support targeting interfaces at all (how would you even persist and interface?).

You can however, declare in the DML that your class implements a given interface. That functionality is not very useful though, as it will simply mark the `_Base` class as implementing the interface, which can be accomplished in a more readable manner by making the non-base class implement it.

**Comment by Maslor** [comment]
Thank you for the quick answer! I thought I had to define interfaces but it wouldn't make much sense as you pointed out.

**Comment by smmf** [comment]
Note, however, that you can define an abstract class, by adding the keyword `abstract` to the non-base class.

**Comment by Maslor** [comment]
Should I add the keyword like ```class abstract Example``` or ```abstract class Example``` @smmf, if I want to define an abstract class? I can't find that in the documentation.

**Comment by smmf** [comment]
The DML is focused on generating the *_Base classes. As a development accelerator the DML compiler also generates the non-base classes *iff they don't exist*, when the compiler is executed. What I proposed was that you could add the abstract keyword to the non-base classe, i.e. after having run the DML compiler at least one, just go and freely edit the non-base class, including adding such keyword.

**Comment by Maslor** [comment]
Oh, I see. Thank you for the clarification @smmf !
